site_name: ToyRL
repo_url: https://github.com/ai-glimpse/toyrl
repo_name: ai-glimpse/toyrl
site_description: A simple and clean reinforcement learning library
site_author: Xiangzhuang Shen
copyright: Copyright &copy; 2025 Xiangzhuang Shen

# Page tree
nav:
  - Home: index.md
  - Algorithms:
      - REINFORCE: algorithms/reinforce.md
      - SARSA: algorithms/sarsa.md
      - DQN: algorithms/dqn.md
      - A2C: algorithms/a2c.md
      - PPO: algorithms/ppo.md
  - Author's website: https://shenxiangzhuang.github.io/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - content.code.annotate

docs_dir: docs


extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shenxiangzhuang/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/xiangzhuang-shen-a81825157/

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets:
      url_download: true
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - admonition
  - attr_list
  - footnotes

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "docs/ieee.csl"
      cite_inline: false
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python-requests.org/en/master/objects.inv
          - https://docs.python.org/3/objects.inv
          - https://mkdocstrings.github.io/objects.inv
          - https://mkdocstrings.github.io/griffe/objects.inv
          - https://python-markdown.github.io/objects.inv
          options:
            show_if_no_docstring: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            show_docstring_classes: true
            show_docstring_attributes: true
            heading_level: 2
            members_order: source
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: false
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_members_full_path: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
