_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-arm64
env:
    value:
        env_name: CartPole-v1
        render_mode: null
        solved_threshold: 475
train:
    value:
        gamma: 0.999
        learning_rate: 0.01
        num_episodes: 100000
        with_baseline: true
